# Generated by Django 5.2.5 on 2025-09-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_category_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
